language: python
node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: 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
  local_dir: build
  on:
    branch: master
